import type { Instrument } from "./types";

/**
 * Monievest ships with a curated, fully simulated market.
 *
 * Every instrument below is a real company, but the prices, volumes and
 * historical series are generated locally by `./engine.ts` from a seed derived
 * from the ticker. No API keys, no network calls, no rate limits — and nothing
 * here should ever be mistaken for a live quote or investment advice.
 */
export const CATALOG: Instrument[] = [
  {
    symbol: "AAPL",
    name: "Apple Inc.",
    kind: "stock",
    sector: "Technology",
    industry: "Consumer Electronics",
    exchange: "NASDAQ",
    price: 227.48,
    changePct: 0.84,
    volatility: 0.24,
    marketCap: 3_440_000_000_000,
    sharesOutstanding: 15_120_000_000,
    pe: 34.1,
    eps: 6.67,
    dividendYield: 0.44,
    beta: 1.24,
    week52High: 237.21,
    week52Low: 164.08,
    avgVolume: 58_400_000,
    ipoYear: 1980,
    hq: "Cupertino, CA",
    employees: "164,000",
    ceo: "Tim Cook",
    color: "#7c6cf6",
    about:
      "Apple designs and sells smartphones, personal computers, tablets, wearables and accessories, alongside a fast-growing services segment spanning the App Store, Apple Music, iCloud, Apple Pay and Apple TV+.",
    tags: ["Mega cap", "Dividend", "Tech leader"],
  },
  {
    symbol: "MSFT",
    name: "Microsoft Corporation",
    kind: "stock",
    sector: "Technology",
    industry: "Software — Infrastructure",
    exchange: "NASDAQ",
    price: 448.62,
    changePct: 1.12,
    volatility: 0.22,
    marketCap: 3_340_000_000_000,
    sharesOutstanding: 7_430_000_000,
    pe: 36.8,
    eps: 12.19,
    dividendYield: 0.68,
    beta: 0.92,
    week52High: 462.3,
    week52Low: 344.79,
    avgVolume: 24_100_000,
    ipoYear: 1986,
    hq: "Redmond, WA",
    employees: "228,000",
    ceo: "Satya Nadella",
    color: "#38bdf8",
    about:
      "Microsoft develops and supports software, services, devices and solutions worldwide: Windows and Devices, Microsoft 365 productivity cloud, LinkedIn, Dynamics, and Azure — one of the largest cloud platforms on earth.",
    tags: ["Mega cap", "Cloud", "AI"],
  },
  {
    symbol: "NVDA",
    name: "NVIDIA Corporation",
    kind: "stock",
    sector: "Technology",
    industry: "Semiconductors",
    exchange: "NASDAQ",
    price: 138.07,
    changePct: 2.41,
    volatility: 0.52,
    marketCap: 3_390_000_000_000,
    sharesOutstanding: 24_560_000_000,
    pe: 52.4,
    eps: 2.63,
    dividendYield: 0.03,
    beta: 1.68,
    week52High: 152.86,
    week52Low: 75.61,
    avgVolume: 212_600_000,
    ipoYear: 1999,
    hq: "Santa Clara, CA",
    employees: "32,100",
    ceo: "Jensen Huang",
    color: "#2ee59b",
    about:
      "NVIDIA is the leading designer of accelerated computing platforms. Its GPUs and CUDA software underpin gaming, professional visualisation, data centres and the training and inference of modern AI models.",
    tags: ["AI", "Semiconductors", "High growth"],
  },
  {
    symbol: "AMZN",
    name: "Amazon.com, Inc.",
    kind: "stock",
    sector: "Consumer Cyclical",
    industry: "Internet Retail",
    exchange: "NASDAQ",
    price: 205.74,
    changePct: -0.42,
    volatility: 0.29,
    marketCap: 2_170_000_000_000,
    sharesOutstanding: 10_540_000_000,
    pe: 39.2,
    eps: 5.25,
    dividendYield: 0,
    beta: 1.15,
    week52High: 215.9,
    week52Low: 151.61,
    avgVolume: 39_700_000,
    ipoYear: 1997,
    hq: "Seattle, WA",
    employees: "1,556,000",
    ceo: "Andy Jassy",
    color: "#f59e0b",
    about:
      "Amazon operates one of the world's largest e-commerce marketplaces and logistics networks, plus AWS — the largest cloud infrastructure provider — alongside advertising, devices and Prime media.",
    tags: ["E-commerce", "Cloud", "Mega cap"],
  },
  {
    symbol: "GOOGL",
    name: "Alphabet Inc. (Class A)",
    kind: "stock",
    sector: "Communication Services",
    industry: "Internet Content & Information",
    exchange: "NASDAQ",
    price: 178.35,
    changePct: 0.63,
    volatility: 0.27,
    marketCap: 2_190_000_000_000,
    sharesOutstanding: 12_280_000_000,
    pe: 23.6,
    eps: 7.56,
    dividendYield: 0.45,
    beta: 1.03,
    week52High: 191.75,
    week52Low: 140.53,
    avgVolume: 27_300_000,
    ipoYear: 2004,
    hq: "Mountain View, CA",
    employees: "183,300",
    ceo: "Sundar Pichai",
    color: "#f472b6",
    about:
      "Alphabet is the parent of Google: search, advertising, Android, Chrome, Maps, YouTube and Google Cloud, plus frontier AI research through DeepMind and a portfolio of 'Other Bets' moonshots.",
    tags: ["Advertising", "AI", "YouTube"],
  },
  {
    symbol: "META",
    name: "Meta Platforms, Inc.",
    kind: "stock",
    sector: "Communication Services",
    industry: "Internet Content & Information",
    exchange: "NASDAQ",
    price: 594.28,
    changePct: 1.74,
    volatility: 0.36,
    marketCap: 1_500_000_000_000,
    sharesOutstanding: 2_530_000_000,
    pe: 27.9,
    eps: 21.3,
    dividendYield: 0.34,
    beta: 1.21,
    week52High: 602.95,
    week52Low: 414.5,
    avgVolume: 15_900_000,
    ipoYear: 2012,
    hq: "Menlo Park, CA",
    employees: "74,100",
    ceo: "Mark Zuckerberg",
    color: "#60a5fa",
    about:
      "Meta builds the Facebook, Instagram, WhatsApp and Messenger family of apps used by billions of people each month, monetised through a highly targeted advertising business, with heavy investment in AI and wearables.",
    tags: ["Social", "Advertising", "AI"],
  },
  {
    symbol: "TSLA",
    name: "Tesla, Inc.",
    kind: "stock",
    sector: "Consumer Cyclical",
    industry: "Auto Manufacturers",
    exchange: "NASDAQ",
    price: 248.91,
    changePct: -1.86,
    volatility: 0.62,
    marketCap: 794_000_000_000,
    sharesOutstanding: 3_190_000_000,
    pe: 74.3,
    eps: 3.35,
    dividendYield: 0,
    beta: 2.31,
    week52High: 278.39,
    week52Low: 138.8,
    avgVolume: 96_200_000,
    ipoYear: 2010,
    hq: "Austin, TX",
    employees: "140,500",
    ceo: "Elon Musk",
    color: "#fb5c78",
    about:
      "Tesla designs, manufactures and sells electric vehicles, battery energy storage systems and solar products, and is developing autonomy software and the Optimus humanoid robot.",
    tags: ["EV", "High beta", "Energy storage"],
  },
  {
    symbol: "AVGO",
    name: "Broadcom Inc.",
    kind: "stock",
    sector: "Technology",
    industry: "Semiconductors",
    exchange: "NASDAQ",
    price: 173.44,
    changePct: 1.28,
    volatility: 0.41,
    marketCap: 810_000_000_000,
    sharesOutstanding: 4_670_000_000,
    pe: 35.7,
    eps: 4.86,
    dividendYield: 1.22,
    beta: 1.18,
    week52High: 184.62,
    week52Low: 119.76,
    avgVolume: 24_800_000,
    ipoYear: 2009,
    hq: "Palo Alto, CA",
    employees: "37,000",
    ceo: "Hock Tan",
    color: "#a78bfa",
    about:
      "Broadcom designs a broad portfolio of semiconductor and infrastructure software solutions — networking, wireless, storage and custom AI accelerators — following its acquisition of VMware.",
    tags: ["Semiconductors", "Dividend", "AI networking"],
  },
  {
    symbol: "JPM",
    name: "JPMorgan Chase & Co.",
    kind: "stock",
    sector: "Financial Services",
    industry: "Banks — Diversified",
    exchange: "NYSE",
    price: 218.6,
    changePct: 0.51,
    volatility: 0.21,
    marketCap: 615_000_000_000,
    sharesOutstanding: 2_810_000_000,
    pe: 12.4,
    eps: 17.63,
    dividendYield: 2.11,
    beta: 1.09,
    week52High: 226.4,
    week52Low: 169.02,
    avgVolume: 9_100_000,
    ipoYear: 1983,
    hq: "New York, NY",
    employees: "309,900",
    ceo: "Jamie Dimon",
    color: "#0ea5e9",
    about:
      "JPMorgan Chase is the largest bank in the United States by assets, serving consumers, corporations and institutions through consumer banking, corporate & investment banking, and asset management.",
    tags: ["Banking", "Dividend", "Blue chip"],
  },
  {
    symbol: "V",
    name: "Visa Inc. (Class A)",
    kind: "stock",
    sector: "Financial Services",
    industry: "Credit Services",
    exchange: "NYSE",
    price: 287.16,
    changePct: -0.28,
    volatility: 0.2,
    marketCap: 570_000_000_000,
    sharesOutstanding: 1_980_000_000,
    pe: 30.2,
    eps: 9.51,
    dividendYield: 0.82,
    beta: 0.94,
    week52High: 297.11,
    week52Low: 246.59,
    avgVolume: 6_400_000,
    ipoYear: 2008,
    hq: "San Francisco, CA",
    employees: "28,800",
    ceo: "Ryan McInerney",
    color: "#2563eb",
    about:
      "Visa operates the world's largest electronic payments network, connecting consumers, merchants, financial institutions and governments across more than 200 countries and territories.",
    tags: ["Payments", "Dividend", "Moat"],
  },
  {
    symbol: "MA",
    name: "Mastercard Incorporated",
    kind: "stock",
    sector: "Financial Services",
    industry: "Credit Services",
    exchange: "NYSE",
    price: 512.4,
    changePct: 0.39,
    volatility: 0.22,
    marketCap: 470_000_000_000,
    sharesOutstanding: 917_000_000,
    pe: 36.4,
    eps: 14.08,
    dividendYield: 0.53,
    beta: 1.11,
    week52High: 529.5,
    week52Low: 420.82,
    avgVolume: 3_100_000,
    ipoYear: 2006,
    hq: "Purchase, NY",
    employees: "33,400",
    ceo: "Michael Miebach",
    color: "#f97316",
    about:
      "Mastercard is a global technology company in the payments industry, operating a processing network that connects consumers, financial institutions, merchants, governments and businesses.",
    tags: ["Payments", "Dividend", "Moat"],
  },
  {
    symbol: "BRK.B",
    name: "Berkshire Hathaway Inc. (Class B)",
    kind: "stock",
    sector: "Financial Services",
    industry: "Insurance — Diversified",
    exchange: "NYSE",
    price: 468.23,
    changePct: 0.22,
    volatility: 0.16,
    marketCap: 1_010_000_000_000,
    sharesOutstanding: 2_160_000_000,
    pe: 9.8,
    eps: 47.78,
    dividendYield: 0,
    beta: 0.87,
    week52High: 474.9,
    week52Low: 372.57,
    avgVolume: 3_300_000,
    ipoYear: 1980,
    hq: "Omaha, NE",
    employees: "396,500",
    ceo: "Greg Abel",
    color: "#64748b",
    about:
      "Berkshire Hathaway is a diversified holding company with subsidiaries in insurance, freight rail, energy, manufacturing, services and retail, plus a large public equity portfolio and cash pile.",
    tags: ["Conglomerate", "Value", "Low beta"],
  },
  {
    symbol: "UNH",
    name: "UnitedHealth Group Incorporated",
    kind: "stock",
    sector: "Healthcare",
    industry: "Healthcare Plans",
    exchange: "NYSE",
    price: 342.77,
    changePct: -1.14,
    volatility: 0.31,
    marketCap: 315_000_000_000,
    sharesOutstanding: 919_000_000,
    pe: 15.6,
    eps: 21.97,
    dividendYield: 2.44,
    beta: 0.64,
    week52High: 630.73,
    week52Low: 270.16,
    avgVolume: 7_800_000,
    ipoYear: 1984,
    hq: "Minnetonka, MN",
    employees: "440,000",
    ceo: "Stephen Hemsley",
    color: "#0d9488",
    about:
      "UnitedHealth Group offers health benefits, coverage and care delivery services through UnitedHealthcare and Optum, serving tens of millions of people across the United States and internationally.",
    tags: ["Healthcare", "Dividend", "Defensive"],
  },
  {
    symbol: "LLY",
    name: "Eli Lilly and Company",
    kind: "stock",
    sector: "Healthcare",
    industry: "Drug Manufacturers — General",
    exchange: "NYSE",
    price: 812.45,
    changePct: 1.96,
    volatility: 0.34,
    marketCap: 771_000_000_000,
    sharesOutstanding: 949_000_000,
    pe: 58.2,
    eps: 13.96,
    dividendYield: 0.79,
    beta: 0.42,
    week52High: 841.3,
    week52Low: 601.94,
    avgVolume: 3_900_000,
    ipoYear: 1970,
    hq: "Indianapolis, IN",
    employees: "46,000",
    ceo: "David Ricks",
    color: "#e879f9",
    about:
      "Eli Lilly discovers, develops and manufactures human pharmaceuticals, with leading franchises in diabetes and obesity care, neuroscience, immunology and oncology.",
    tags: ["Pharma", "GLP-1", "Growth"],
  },
  {
    symbol: "JNJ",
    name: "Johnson & Johnson",
    kind: "stock",
    sector: "Healthcare",
    industry: "Drug Manufacturers — General",
    exchange: "NYSE",
    price: 156.32,
    changePct: 0.18,
    volatility: 0.15,
    marketCap: 376_000_000_000,
    sharesOutstanding: 2_406_000_000,
    pe: 15.1,
    eps: 10.35,
    dividendYield: 3.18,
    beta: 0.52,
    week52High: 168.85,
    week52Low: 143.13,
    avgVolume: 8_200_000,
    ipoYear: 1944,
    hq: "New Brunswick, NJ",
    employees: "131,900",
    ceo: "Joaquin Duato",
    color: "#ef4444",
    about:
      "Johnson & Johnson is a global healthcare company focused on innovative medicine and medtech, with a portfolio spanning oncology, immunology, neuroscience, cardiovascular and surgical solutions.",
    tags: ["Dividend king", "Defensive", "Medtech"],
  },
  {
    symbol: "XOM",
    name: "Exxon Mobil Corporation",
    kind: "stock",
    sector: "Energy",
    industry: "Oil & Gas Integrated",
    exchange: "NYSE",
    price: 118.94,
    changePct: -0.67,
    volatility: 0.23,
    marketCap: 524_000_000_000,
    sharesOutstanding: 4_400_000_000,
    pe: 14.2,
    eps: 8.38,
    dividendYield: 3.36,
    beta: 0.88,
    week52High: 126.34,
    week52Low: 100.96,
    avgVolume: 17_400_000,
    ipoYear: 1970,
    hq: "Irving, TX",
    employees: "61,000",
    ceo: "Darren Woods",
    color: "#dc2626",
    about:
      "Exxon Mobil is one of the largest publicly traded oil and gas companies, exploring, producing, refining and marketing crude oil, natural gas and petrochemical products worldwide.",
    tags: ["Energy", "Dividend", "Value"],
  },
  {
    symbol: "CVX",
    name: "Chevron Corporation",
    kind: "stock",
    sector: "Energy",
    industry: "Oil & Gas Integrated",
    exchange: "NYSE",
    price: 154.08,
    changePct: -0.91,
    volatility: 0.24,
    marketCap: 285_000_000_000,
    sharesOutstanding: 1_850_000_000,
    pe: 16.4,
    eps: 9.4,
    dividendYield: 4.28,
    beta: 1.12,
    week52High: 167.11,
    week52Low: 135.37,
    avgVolume: 10_600_000,
    ipoYear: 1970,
    hq: "Houston, TX",
    employees: "45,600",
    ceo: "Mike Wirth",
    color: "#2563eb",
    about:
      "Chevron is an integrated energy company producing oil and natural gas, manufacturing transportation fuels, lubricants and petrochemicals, and developing lower-carbon businesses.",
    tags: ["Energy", "Dividend", "Value"],
  },
  {
    symbol: "WMT",
    name: "Walmart Inc.",
    kind: "stock",
    sector: "Consumer Defensive",
    industry: "Discount Stores",
    exchange: "NYSE",
    price: 82.36,
    changePct: 0.44,
    volatility: 0.18,
    marketCap: 662_000_000_000,
    sharesOutstanding: 8_030_000_000,
    pe: 33.6,
    eps: 2.45,
    dividendYield: 1.01,
    beta: 0.51,
    week52High: 85.62,
    week52Low: 58.31,
    avgVolume: 18_900_000,
    ipoYear: 1972,
    hq: "Bentonville, AR",
    employees: "2,100,000",
    ceo: "Doug McMillon",
    color: "#facc15",
    about:
      "Walmart operates a chain of hypermarkets, discount stores and grocery stores across 19 countries, plus a rapidly growing e-commerce, advertising and membership business.",
    tags: ["Retail", "Defensive", "Dividend"],
  },
  {
    symbol: "COST",
    name: "Costco Wholesale Corporation",
    kind: "stock",
    sector: "Consumer Defensive",
    industry: "Discount Stores",
    exchange: "NASDAQ",
    price: 921.7,
    changePct: 0.61,
    volatility: 0.19,
    marketCap: 408_000_000_000,
    sharesOutstanding: 443_000_000,
    pe: 55.8,
    eps: 16.52,
    dividendYield: 0.51,
    beta: 0.79,
    week52High: 942.1,
    week52Low: 699.75,
    avgVolume: 2_400_000,
    ipoYear: 1985,
    hq: "Issaquah, WA",
    employees: "333,000",
    ceo: "Ron Vachris",
    color: "#e11d48",
    about:
      "Costco is the largest membership warehouse club operator, generating most of its operating income from membership fees while selling groceries, appliances, fuel and travel at near-cost prices.",
    tags: ["Retail", "Membership", "Compounder"],
  },
  {
    symbol: "PG",
    name: "The Procter & Gamble Company",
    kind: "stock",
    sector: "Consumer Defensive",
    industry: "Household & Personal Products",
    exchange: "NYSE",
    price: 168.42,
    changePct: -0.24,
    volatility: 0.14,
    marketCap: 396_000_000_000,
    sharesOutstanding: 2_350_000_000,
    pe: 26.3,
    eps: 6.4,
    dividendYield: 2.42,
    beta: 0.42,
    week52High: 176.9,
    week52Low: 149.62,
    avgVolume: 7_100_000,
    ipoYear: 1970,
    hq: "Cincinnati, OH",
    employees: "112,000",
    ceo: "Shailesh Jejurikar",
    color: "#0891b2",
    about:
      "Procter & Gamble provides branded consumer packaged goods to billions of people: fabric & home care, baby/feminine/family care, beauty, grooming and health care.",
    tags: ["Dividend king", "Defensive", "Staples"],
  },
  {
    symbol: "KO",
    name: "The Coca-Cola Company",
    kind: "stock",
    sector: "Consumer Defensive",
    industry: "Beverages — Non-Alcoholic",
    exchange: "NYSE",
    price: 71.28,
    changePct: 0.12,
    volatility: 0.13,
    marketCap: 307_000_000_000,
    sharesOutstanding: 4_310_000_000,
    pe: 26.9,
    eps: 2.65,
    dividendYield: 2.78,
    beta: 0.46,
    week52High: 74.38,
    week52Low: 60.44,
    avgVolume: 13_600_000,
    ipoYear: 1919,
    hq: "Atlanta, GA",
    employees: "79,100",
    ceo: "James Quincey",
    color: "#b91c1c",
    about:
      "Coca-Cola is the world's largest beverage company, marketing more than 200 brands of sparkling soft drinks, water, sports drinks, juice, coffee and tea through a global bottling network.",
    tags: ["Dividend king", "Defensive", "Global brand"],
  },
  {
    symbol: "NFLX",
    name: "Netflix, Inc.",
    kind: "stock",
    sector: "Communication Services",
    industry: "Entertainment",
    exchange: "NASDAQ",
    price: 698.34,
    changePct: 1.42,
    volatility: 0.38,
    marketCap: 299_000_000_000,
    sharesOutstanding: 428_000_000,
    pe: 41.2,
    eps: 16.95,
    dividendYield: 0,
    beta: 1.31,
    week52High: 715.4,
    week52Low: 471.12,
    avgVolume: 3_600_000,
    ipoYear: 2002,
    hq: "Los Gatos, CA",
    employees: "14,000",
    ceo: "Ted Sarandos",
    color: "#dc2626",
    about:
      "Netflix is the world's leading subscription streaming entertainment service, delivering series, films and games to hundreds of millions of paid members in more than 190 countries.",
    tags: ["Streaming", "Growth", "Media"],
  },
  {
    symbol: "DIS",
    name: "The Walt Disney Company",
    kind: "stock",
    sector: "Communication Services",
    industry: "Entertainment",
    exchange: "NYSE",
    price: 96.41,
    changePct: -0.55,
    volatility: 0.26,
    marketCap: 174_000_000_000,
    sharesOutstanding: 1_800_000_000,
    pe: 19.8,
    eps: 4.87,
    dividendYield: 1.03,
    beta: 1.33,
    week52High: 123.74,
    week52Low: 83.91,
    avgVolume: 10_900_000,
    ipoYear: 1940,
    hq: "Burbank, CA",
    employees: "231,000",
    ceo: "Bob Iger",
    color: "#3b82f6",
    about:
      "Disney operates entertainment, sports and experiences segments: film and television studios, streaming services including Disney+ and Hulu, theme parks, cruises and consumer products.",
    tags: ["Media", "Parks", "Turnaround"],
  },
  {
    symbol: "AMD",
    name: "Advanced Micro Devices, Inc.",
    kind: "stock",
    sector: "Technology",
    industry: "Semiconductors",
    exchange: "NASDAQ",
    price: 164.28,
    changePct: 2.86,
    volatility: 0.55,
    marketCap: 266_000_000_000,
    sharesOutstanding: 1_620_000_000,
    pe: 108.4,
    eps: 1.52,
    dividendYield: 0,
    beta: 1.71,
    week52High: 172.33,
    week52Low: 116.37,
    avgVolume: 41_300_000,
    ipoYear: 1972,
    hq: "Santa Clara, CA",
    employees: "26,000",
    ceo: "Lisa Su",
    color: "#16a34a",
    about:
      "AMD is a high-performance and adaptive computing leader, producing CPUs, GPUs, FPGAs and adaptive SoCs for data centres, client computing, gaming and embedded markets.",
    tags: ["Semiconductors", "AI", "High beta"],
  },
  {
    symbol: "CRM",
    name: "Salesforce, Inc.",
    kind: "stock",
    sector: "Technology",
    industry: "Software — Application",
    exchange: "NYSE",
    price: 272.15,
    changePct: -1.32,
    volatility: 0.33,
    marketCap: 261_000_000_000,
    sharesOutstanding: 960_000_000,
    pe: 39.7,
    eps: 6.85,
    dividendYield: 0.6,
    beta: 1.21,
    week52High: 318.71,
    week52Low: 212.0,
    avgVolume: 6_900_000,
    ipoYear: 2004,
    hq: "San Francisco, CA",
    employees: "72,600",
    ceo: "Marc Benioff",
    color: "#0ea5e9",
    about:
      "Salesforce provides customer relationship management software and enterprise cloud applications for sales, service, marketing, commerce and data — now layered with its Agentforce AI platform.",
    tags: ["SaaS", "Enterprise", "AI agents"],
  },
  {
    symbol: "ADBE",
    name: "Adobe Inc.",
    kind: "stock",
    sector: "Technology",
    industry: "Software — Application",
    exchange: "NASDAQ",
    price: 512.9,
    changePct: 0.74,
    volatility: 0.31,
    marketCap: 221_000_000_000,
    sharesOutstanding: 431_000_000,
    pe: 42.6,
    eps: 12.04,
    dividendYield: 0,
    beta: 1.19,
    week52High: 587.65,
    week52Low: 403.75,
    avgVolume: 3_800_000,
    ipoYear: 1986,
    hq: "San Jose, CA",
    employees: "29,900",
    ceo: "Shantanu Narayen",
    color: "#ef4444",
    about:
      "Adobe builds creative, marketing and document software — Creative Cloud, Document Cloud and Experience Cloud — with Firefly generative AI embedded across its products.",
    tags: ["SaaS", "Creative", "Generative AI"],
  },
  {
    symbol: "ORCL",
    name: "Oracle Corporation",
    kind: "stock",
    sector: "Technology",
    industry: "Software — Infrastructure",
    exchange: "NYSE",
    price: 245.62,
    changePct: 3.18,
    volatility: 0.44,
    marketCap: 690_000_000_000,
    sharesOutstanding: 2_810_000_000,
    pe: 47.2,
    eps: 5.2,
    dividendYield: 0.72,
    beta: 1.06,
    week52High: 251.44,
    week52Low: 121.53,
    avgVolume: 15_200_000,
    ipoYear: 1986,
    hq: "Austin, TX",
    employees: "159,000",
    ceo: "Clay Magouyrk",
    color: "#dc2626",
    about:
      "Oracle offers database software, cloud engineered systems and enterprise software products, with Oracle Cloud Infrastructure becoming a major supplier of AI training capacity.",
    tags: ["Cloud", "Databases", "AI infrastructure"],
  },
  {
    symbol: "INTC",
    name: "Intel Corporation",
    kind: "stock",
    sector: "Technology",
    industry: "Semiconductors",
    exchange: "NASDAQ",
    price: 30.84,
    changePct: -2.41,
    volatility: 0.58,
    marketCap: 132_000_000_000,
    sharesOutstanding: 4_280_000_000,
    pe: null,
    eps: -0.42,
    dividendYield: 0,
    beta: 1.28,
    week52High: 32.4,
    week52Low: 18.51,
    avgVolume: 88_400_000,
    ipoYear: 1971,
    hq: "Santa Clara, CA",
    employees: "96,400",
    ceo: "Lip-Bu Tan",
    color: "#60a5fa",
    about:
      "Intel designs, manufactures and sells essential advanced technology products — CPUs, chipsets, GPUs and foundry services — and is mid-way through a large-scale turnaround of its process roadmap.",
    tags: ["Semiconductors", "Turnaround", "Foundry"],
  },
  {
    symbol: "BA",
    name: "The Boeing Company",
    kind: "stock",
    sector: "Industrials",
    industry: "Aerospace & Defense",
    exchange: "NYSE",
    price: 178.29,
    changePct: -0.83,
    volatility: 0.4,
    marketCap: 134_000_000_000,
    sharesOutstanding: 750_000_000,
    pe: null,
    eps: -5.14,
    dividendYield: 0,
    beta: 1.53,
    week52High: 196.95,
    week52Low: 128.88,
    avgVolume: 8_700_000,
    ipoYear: 1934,
    hq: "Arlington, VA",
    employees: "171,000",
    ceo: "Kelly Ortberg",
    color: "#2563eb",
    about:
      "Boeing develops, manufactures and sells commercial jetliners, defence products, space systems and services, and is working through a multi-year safety, quality and delivery recovery plan.",
    tags: ["Aerospace", "Cyclical", "Turnaround"],
  },
  {
    symbol: "CAT",
    name: "Caterpillar Inc.",
    kind: "stock",
    sector: "Industrials",
    industry: "Farm & Heavy Construction Machinery",
    exchange: "NYSE",
    price: 361.44,
    changePct: 0.96,
    volatility: 0.26,
    marketCap: 173_000_000_000,
    sharesOutstanding: 479_000_000,
    pe: 19.4,
    eps: 18.63,
    dividendYield: 1.53,
    beta: 1.05,
    week52High: 374.2,
    week52Low: 283.11,
    avgVolume: 3_200_000,
    ipoYear: 1929,
    hq: "Irving, TX",
    employees: "113,200",
    ceo: "Joe Creed",
    color: "#eab308",
    about:
      "Caterpillar is the world's leading manufacturer of construction and mining equipment, diesel and natural gas engines, industrial gas turbines and diesel-electric locomotives.",
    tags: ["Industrials", "Dividend", "Infrastructure"],
  },
  {
    symbol: "GE",
    name: "GE Aerospace",
    kind: "stock",
    sector: "Industrials",
    industry: "Aerospace & Defense",
    exchange: "NYSE",
    price: 208.71,
    changePct: 1.19,
    volatility: 0.3,
    marketCap: 226_000_000_000,
    sharesOutstanding: 1_080_000_000,
    pe: 32.1,
    eps: 6.5,
    dividendYield: 0.61,
    beta: 1.38,
    week52High: 216.3,
    week52Low: 142.06,
    avgVolume: 6_100_000,
    ipoYear: 1962,
    hq: "Evendale, OH",
    employees: "52,000",
    ceo: "Larry Culp",
    color: "#0891b2",
    about:
      "GE Aerospace designs, produces and services jet engines for commercial and military aircraft, earning most of its profit from a large installed base of aftermarket parts and services.",
    tags: ["Aerospace", "Aftermarket", "Dividend"],
  },
  {
    symbol: "NKE",
    name: "NIKE, Inc. (Class B)",
    kind: "stock",
    sector: "Consumer Cyclical",
    industry: "Footwear & Accessories",
    exchange: "NYSE",
    price: 78.14,
    changePct: -0.62,
    volatility: 0.28,
    marketCap: 118_000_000_000,
    sharesOutstanding: 1_510_000_000,
    pe: 28.6,
    eps: 2.73,
    dividendYield: 1.84,
    beta: 1.03,
    week52High: 107.44,
    week52Low: 68.62,
    avgVolume: 12_400_000,
    ipoYear: 1980,
    hq: "Beaverton, OR",
    employees: "77,800",
    ceo: "Elliott Hill",
    color: "#111827",
    about:
      "NIKE designs, develops and markets athletic footwear, apparel, equipment and accessories worldwide under the NIKE, Jordan and Converse brands.",
    tags: ["Consumer", "Brand", "Turnaround"],
  },
  {
    symbol: "HD",
    name: "The Home Depot, Inc.",
    kind: "stock",
    sector: "Consumer Cyclical",
    industry: "Home Improvement Retail",
    exchange: "NYSE",
    price: 402.18,
    changePct: 0.27,
    volatility: 0.19,
    marketCap: 399_000_000_000,
    sharesOutstanding: 993_000_000,
    pe: 27.4,
    eps: 14.68,
    dividendYield: 2.29,
    beta: 1.03,
    week52High: 418.5,
    week52Low: 323.77,
    avgVolume: 4_600_000,
    ipoYear: 1981,
    hq: "Atlanta, GA",
    employees: "463,100",
    ceo: "Ted Decker",
    color: "#f97316",
    about:
      "Home Depot is the world's largest home improvement retailer, selling tools, building products, lawn and garden supplies and décor, and providing installation services.",
    tags: ["Retail", "Dividend", "Housing-linked"],
  },
  {
    symbol: "MCD",
    name: "McDonald's Corporation",
    kind: "stock",
    sector: "Consumer Cyclical",
    industry: "Restaurants",
    exchange: "NYSE",
    price: 301.66,
    changePct: 0.15,
    volatility: 0.15,
    marketCap: 216_000_000_000,
    sharesOutstanding: 716_000_000,
    pe: 26.8,
    eps: 11.26,
    dividendYield: 2.31,
    beta: 0.7,
    week52High: 311.4,
    week52Low: 245.2,
    avgVolume: 3_400_000,
    ipoYear: 1965,
    hq: "Chicago, IL",
    employees: "150,000",
    ceo: "Chris Kempczinski",
    color: "#eab308",
    about:
      "McDonald's is the world's largest restaurant chain by revenue, operating an overwhelmingly franchised model that generates highly predictable royalty and rent income.",
    tags: ["Franchise", "Dividend", "Defensive"],
  },
  {
    symbol: "SBUX",
    name: "Starbucks Corporation",
    kind: "stock",
    sector: "Consumer Cyclical",
    industry: "Restaurants",
    exchange: "NASDAQ",
    price: 92.48,
    changePct: -1.08,
    volatility: 0.27,
    marketCap: 104_000_000_000,
    sharesOutstanding: 1_130_000_000,
    pe: 32.4,
    eps: 2.85,
    dividendYield: 2.68,
    beta: 0.94,
    week52High: 99.62,
    week52Low: 71.02,
    avgVolume: 9_800_000,
    ipoYear: 1992,
    hq: "Seattle, WA",
    employees: "360,000",
    ceo: "Brian Niccol",
    color: "#15803d",
    about:
      "Starbucks roasts, markets and distributes specialty coffee and tea and operates tens of thousands of company and licensed stores in more than 80 markets.",
    tags: ["Restaurants", "Dividend", "Recovery"],
  },
  {
    symbol: "COIN",
    name: "Coinbase Global, Inc.",
    kind: "stock",
    sector: "Financial Services",
    industry: "Financial Data & Stock Exchanges",
    exchange: "NASDAQ",
    price: 268.44,
    changePct: 4.12,
    volatility: 0.78,
    marketCap: 68_000_000_000,
    sharesOutstanding: 253_000_000,
    pe: 41.8,
    eps: 6.42,
    dividendYield: 0,
    beta: 3.12,
    week52High: 308.48,
    week52Low: 142.17,
    avgVolume: 12_700_000,
    ipoYear: 2021,
    hq: "Wilmington, DE",
    employees: "3,772",
    ceo: "Brian Armstrong",
    color: "#2563eb",
    about:
      "Coinbase operates a regulated cryptocurrency exchange platform for retail and institutional users, offering trading, custody, staking and subscription services.",
    tags: ["Crypto", "High beta", "Speculative"],
  },
  {
    symbol: "PLTR",
    name: "Palantir Technologies Inc.",
    kind: "stock",
    sector: "Technology",
    industry: "Software — Infrastructure",
    exchange: "NASDAQ",
    price: 42.18,
    changePct: 3.44,
    volatility: 0.68,
    marketCap: 98_000_000_000,
    sharesOutstanding: 2_320_000_000,
    pe: 96.2,
    eps: 0.44,
    dividendYield: 0,
    beta: 2.62,
    week52High: 44.6,
    week52Low: 20.11,
    avgVolume: 62_300_000,
    ipoYear: 2020,
    hq: "Denver, CO",
    employees: "3,936",
    ceo: "Alex Karp",
    color: "#0f172a",
    about:
      "Palantir builds big-data analytics platforms — Gotham for government and defence, Foundry for commercial enterprises, and AIP for deploying AI inside operating workflows.",
    tags: ["AI", "Government", "High beta"],
  },
  {
    symbol: "NEE",
    name: "NextEra Energy, Inc.",
    kind: "stock",
    sector: "Utilities",
    industry: "Utilities — Regulated Electric",
    exchange: "NYSE",
    price: 74.86,
    changePct: 0.34,
    volatility: 0.19,
    marketCap: 154_000_000_000,
    sharesOutstanding: 2_060_000_000,
    pe: 22.6,
    eps: 3.31,
    dividendYield: 2.83,
    beta: 0.62,
    week52High: 78.4,
    week52Low: 61.72,
    avgVolume: 11_200_000,
    ipoYear: 1983,
    hq: "Juno Beach, FL",
    employees: "16,000",
    ceo: "John Ketchum",
    color: "#14b8a6",
    about:
      "NextEra Energy operates Florida Power & Light, the largest electric utility in the US, and NextEra Energy Resources, one of the largest generators of renewable energy from wind and solar.",
    tags: ["Utilities", "Renewables", "Dividend"],
  },
  {
    symbol: "PLD",
    name: "Prologis, Inc.",
    kind: "stock",
    sector: "Real Estate",
    industry: "REIT — Industrial",
    exchange: "NYSE",
    price: 112.34,
    changePct: -0.38,
    volatility: 0.22,
    marketCap: 104_000_000_000,
    sharesOutstanding: 926_000_000,
    pe: 34.2,
    eps: 3.28,
    dividendYield: 3.42,
    beta: 1.02,
    week52High: 125.4,
    week52Low: 102.3,
    avgVolume: 5_100_000,
    ipoYear: 1997,
    hq: "San Francisco, CA",
    employees: "2,540",
    ceo: "Hamid Moghadam",
    color: "#f59e0b",
    about:
      "Prologis is the largest owner and operator of logistics real estate — distribution centres and warehouses in key consumption markets worldwide — plus a growing energy business.",
    tags: ["REIT", "Logistics", "Dividend"],
  },
  {
    symbol: "LIN",
    name: "Linde plc",
    kind: "stock",
    sector: "Basic Materials",
    industry: "Specialty Chemicals",
    exchange: "NASDAQ",
    price: 462.11,
    changePct: 0.42,
    volatility: 0.17,
    marketCap: 220_000_000_000,
    sharesOutstanding: 476_000_000,
    pe: 33.4,
    eps: 13.84,
    dividendYield: 1.29,
    beta: 0.86,
    week52High: 474.9,
    week52Low: 408.65,
    avgVolume: 2_100_000,
    ipoYear: 1992,
    hq: "Guildford, UK",
    employees: "66,300",
    ceo: "Sanjiv Lamba",
    color: "#0ea5e9",
    about:
      "Linde is the world's largest industrial gases and engineering company, producing atmospheric and process gases for healthcare, refining, chemicals, metals and electronics.",
    tags: ["Industrials", "Dividend", "Compounder"],
  },
  {
    symbol: "SPY",
    name: "SPDR S&P 500 ETF Trust",
    kind: "etf",
    sector: "Funds & ETFs",
    industry: "Exchange Traded Fund",
    exchange: "NYSEARCA",
    price: 646.18,
    changePct: 0.58,
    volatility: 0.14,
    marketCap: 610_000_000_000,
    sharesOutstanding: 944_000_000,
    pe: 24.1,
    eps: 26.81,
    dividendYield: 1.21,
    beta: 1.0,
    week52High: 652.4,
    week52Low: 482.63,
    avgVolume: 52_700_000,
    ipoYear: 1993,
    hq: "New York, NY",
    employees: "—",
    ceo: "Michael Feehily",
    color: "#7c6cf6",
    about:
      "SPY tracks the S&P 500 Index, giving a single-line holding in 500 of the largest US companies. It is the most heavily traded security in the world and a core building block for diversified portfolios.",
    tags: ["Index fund", "Diversified", "Core holding"],
  },
  {
    symbol: "QQQ",
    name: "Invesco QQQ Trust",
    kind: "etf",
    sector: "Funds & ETFs",
    industry: "Exchange Traded Fund",
    exchange: "NASDAQ",
    price: 512.44,
    changePct: 1.04,
    volatility: 0.19,
    marketCap: 300_000_000_000,
    sharesOutstanding: 585_000_000,
    pe: 31.2,
    eps: 16.42,
    dividendYield: 0.51,
    beta: 1.17,
    week52High: 518.2,
    week52Low: 390.61,
    avgVolume: 33_900_000,
    ipoYear: 1999,
    hq: "New York, NY",
    employees: "—",
    ceo: "Aden Buthani",
    color: "#38bdf8",
    about:
      "QQQ tracks the Nasdaq-100 Index — 100 of the largest non-financial companies listed on Nasdaq — and is the standard vehicle for concentrated exposure to US large-cap growth and technology.",
    tags: ["Index fund", "Growth", "Tech heavy"],
  },
  {
    symbol: "VTI",
    name: "Vanguard Total Stock Market ETF",
    kind: "etf",
    sector: "Funds & ETFs",
    industry: "Exchange Traded Fund",
    exchange: "NYSEARCA",
    price: 292.63,
    changePct: 0.52,
    volatility: 0.14,
    marketCap: 1_700_000_000_000,
    sharesOutstanding: 5_810_000_000,
    pe: 24.4,
    eps: 11.99,
    dividendYield: 1.24,
    beta: 1.0,
    week52High: 295.1,
    week52Low: 218.4,
    avgVolume: 4_300_000,
    ipoYear: 2001,
    hq: "Malvern, PA",
    employees: "—",
    ceo: "Salim Ramji",
    color: "#2ee59b",
    about:
      "VTI tracks the CRSP US Total Market Index, covering nearly 4,000 large, mid, small and micro-cap US companies in a single low-cost fund — a popular one-fund portfolio.",
    tags: ["Index fund", "Total market", "Low cost"],
  },
  {
    symbol: "ARKK",
    name: "ARK Innovation ETF",
    kind: "etf",
    sector: "Funds & ETFs",
    industry: "Exchange Traded Fund",
    exchange: "NYSEARCA",
    price: 68.92,
    changePct: 2.24,
    volatility: 0.52,
    marketCap: 6_800_000_000,
    sharesOutstanding: 98_700_000,
    pe: null,
    eps: null,
    dividendYield: 0,
    beta: 2.04,
    week52High: 72.4,
    week52Low: 37.1,
    avgVolume: 14_200_000,
    ipoYear: 2014,
    hq: "St. Petersburg, FL",
    employees: "—",
    ceo: "Cathie Wood",
    color: "#f472b6",
    about:
      "ARKK is an actively managed ETF seeking long-term capital appreciation through disruptive innovation themes: AI, robotics, genomics, digital assets and next-generation internet.",
    tags: ["Active", "Disruptive innovation", "High beta"],
  },
];

export const INSTRUMENTS_BY_SYMBOL: Record<string, Instrument> = Object.fromEntries(
  CATALOG.map((instrument) => [instrument.symbol, instrument]),
);

export const SECTORS: Instrument["sector"][] = Array.from(
  new Set(CATALOG.map((instrument) => instrument.sector)),
).sort();

export function getInstrument(symbol: string): Instrument | undefined {
  return INSTRUMENTS_BY_SYMBOL[symbol.toUpperCase()];
}

export function getInstrumentOrThrow(symbol: string): Instrument {
  const instrument = getInstrument(symbol);
  if (!instrument) throw new Error(`Unknown instrument: ${symbol}`);
  return instrument;
}
